#pragma once


namespace Client
{
	enum PLAYER_ANIM {
		PLAYER_IMPACT_DEFLECT_R,

		PLAYER_ACTION_DRAGONHEART,
		PLAYER_ACTION_DRAGONSTONE,
		PLAYER_ACTION_POWERSTONE,
		PLAYER_ACTION_RUNEKEYHOLE,
		PLAYER_ACTION_TELEPORT_LONG_ENTER,
		PLAYER_ACTION_TELEPORT_LONG_EXIT,
		PLAYER_ACTION_TELEPORT_LONG_IDLE,
		PLAYER_ACTION_WAYPOINT_GRAB,
		PLAYER_ACTION_WAYPOINT_GRAB_IDLE,
		PLAYER_ACTION_WAYPOINT_KNOCKDOWN,
		PLAYER_ACTION_WAYPOINT_RELEASE,

		PLAYER_JUMP_FALL,

		PLAYER_IMPACT_DEATH_F,	// 앞으로 쓰러짐
		PLAYER_IMPACT_DEATH_B,	// 뒤로 쓰러짐
		PLAYER_IMPACT_DEFLECT_L,
		PLAYER_IMPACT_HEAVY_FROMB,
		PLAYER_IMPACT_HEAVY_FROMF,
		PLAYER_IMPACT_MASSIVE_FROMB,
		PLAYER_IMPACT_MASSIVE_FROMF,
		PLAYER_IMPACT_STUN_FROMF,

		PLAYER_BLOCK_COUNTER,
		PLAYER_BLOCK_IDLE,
		PLAYER_BLOCK_IMPACT,
		PLAYER_BLOCK_IMPACT_BREAK,
		PLAYER_BLOCK_START,
		PLAYER_BLOCK_TURN_L,
		PLAYER_BLOCK_TURN_R,
		PLAYER_BLOCK_WALK_B,
		PLAYER_BLOCK_WALK_F,
		PLAYER_BLOCK_WALK_L,
		PLAYER_BLOCK_WALK_R,

		PLAYER_ATK_BACK,
		PLAYER_ATK_DODGE_B,
		PLAYER_ATK_DODGE_L,
		PLAYER_ATK_DODGE_R,
		PLAYER_ATK_LIGHT_01,
		PLAYER_ATK_LIGHT_02,
		PLAYER_ATK_LIGHT_03,
		PLAYER_ATK_LIGHT_04,
		PLAYER_ATK_POWER_01,
		PLAYER_ATK_POWER_01_CHARGE,
		PLAYER_ATK_POWER_02,
		PLAYER_ATK_POWER_02_CHARGE,
		PLAYER_ATK_RUN,

		PLAYER_MOVE_DODGE_B,
		PLAYER_MOVE_DODGE_F,
		PLAYER_MOVE_DODGE_L,
		PLAYER_MOVE_DODGE_R,
		PLAYER_MOVE_IDLE,
		PLAYER_MOVE_JOG_B,
		PLAYER_MOVE_JOG_F,
		PLAYER_MOVE_JOG_F_D,
		PLAYER_MOVE_JOG_F_U,
		PLAYER_MOVE_JOG_L,
		PLAYER_MOVE_JOG_R,
		PLAYER_MOVE_TURN_L,
		PLAYER_MOVE_TURN_R,
		PLAYER_MOVE_WALK_B,
		PLAYER_MOVE_WALK_F,
		PLAYER_MOVE_WALK_F_D,
		PLAYER_MOVE_WALK_F_U,
		PLAYER_MOVE_WALK_L,
		PLAYER_MOVE_WALK_R,

		PLAYER_ANIM_END
	};
	enum BOSS_ANIM
	{
		BOSS_LAB_ATK_180,

		BOSS_LAB_ATK_BEAM,
		BOSS_LAB_ATK_BEAM_INTO,
		BOSS_LAB_ATK_BEAM_OUT,
		BOSS_LAB_ATK_BEAM_SWEEP_L,
		BOSS_LAB_ATK_BEAM_SWEEP_R,
		BOSS_LAB_ATK_BEAM_TURN_L,
		BOSS_LAB_ATK_BEAM_TURN_R,
		
		BOSS_LAB_ATK_CHARGE,
		BOSS_LAB_ATK_CHARGE_INTO,
		BOSS_LAB_ATK_CHARGE_OUT,
		
		BOSS_LAB_ATK_DOUBLE_SWIPE,
		
		BOSS_LAB_ATK_RUSH,
		
		BOSS_LAB_ATK_SWIPE_L,
		BOSS_LAB_ATK_SWIPE_R,

		BOSS_LAB_IDLE,
		BOSS_LAB_IDLE_LEFT,
		BOSS_LAB_IDLE_RIGHT,
		BOSS_LAB_IMPACT_DEATH,

		BOSS_LAB_JUMP_180,

		BOSS_LAB_STUN,
		BOSS_LAB_STUN_IDLE,
		BOSS_LAB_STUN_IMPACT,
		BOSS_LAB_STUN_WAKEUP,

		BOSS_LAB_TELEPORT_APPEAR,
		BOSS_LAB_TELEPORT_LAUNCH,
		BOSS_LAB_TELEPORT_LAUNCH_ROAR,
		BOSS_LAB_TELEPORT_LAUNCH_UNDERGROUND,
		BOSS_LAB_TELEPORT_START,

		BOSS_LAB_TURN_L_90,
		BOSS_LAB_TURN_R_90,

		BOSS_LAB_WALK_START,
		BOSS_LAB_WALK_STOP,
		BOSS_LAB_WALKF,

		BOSS_ANIM_END
	};
}